# Generated by Django 2.1.7 on 2019-02-24 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DoorCode',
            new_name='registro',
        ),
    ]
