# Generated by Django 2.1.7 on 2019-02-24 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_auto_20190223_1837'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registro',
            name='code',
        ),
        migrations.AddField(
            model_name='registro',
            name='nombre',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registro',
            name='password',
            field=models.CharField(default='jola', max_length=8),
            preserve_default=False,
        ),
    ]
