# Generated by Django 2.1.7 on 2019-02-24 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_auto_20190223_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='email',
            field=models.CharField(default='csi', max_length=50),
            preserve_default=False,
        ),
    ]
