# Generated by Django 2.1.7 on 2019-02-24 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_auto_20190223_2148'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='registro',
            table='registro',
        ),
    ]
