# Generated by Django 2.1.7 on 2019-04-04 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0006_auto_20190223_2224'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiRegistro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=8)),
                ('email', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'api_registro',
                'managed': False,
            },
        ),
    ]
